image: jangorecki/r-data.table-pg
services:
- postgres

variables:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

pages:
  script:
    # non-R dependencies
    - apt-get update -qy
    - apt-get install -y libpq-dev
    # build pkg
    - R CMD build . --no-build-vignettes --no-manual
    # install deps
    - Rscript -e 'install.packages(c("RPostgreSQL","data.table"), repos="https://cran.rstudio.com")'
    # install suggests
    - Rscript -e 'install.packages(c("microbenchmarkCore","logR"), repos = c("https://jangorecki.github.io/logR","https://olafmersmann.github.io/drat","https://cran.rstudio.com"))'
    # run check
    - R CMD check $(ls -1t *.tar.gz | head -n 1) --no-vignettes --no-build-vignettes --no-manual --as-cran
    # gl-pages dir and Rcheck results dir
    - mkdir public Rcheck
    # export Rcheck results
    - mv $(find . -maxdepth 1 -name "*.Rcheck" -type d) Rcheck
    # install drat with `packageHtml` function
    - Rscript -e 'install.packages("drat", repos = "https://jangorecki.github.io/drat")'
    # produce drat repo
    - Rscript -e 'drat::insertPackage(list.files(pattern = "*\\.tar\\.gz$"), repodir = "public")'
    # produce html homepage and manual
    - Rscript -e 'drat::packageHtml(repodir = "public", repo.url = "https://jangorecki.github.io/big.data.table", repo.cran = TRUE, manual = TRUE)'
  only:
    - master
  artifacts:
    paths:
      - Rcheck
      - public
